# dialogs/rapport_mhh_dialog.py

from .base_rapport_dialog import BaseRapportDialog

class RapportMHH(BaseRapportDialog):
    def __init__(self):

        champs = [
            "Nom_Station",
            "Type_Peupl",
            "Typ_Peupl_Det",
            "Date",
            "Heure",
            "Evalu_Princ",
            "num_echant",
            "Contexte",
            "Situat",
            "FormTerr",
            "Depress",
            "Depres_Pct",
            "Montic_Pct",
            "Veg_Pert",
            "Sol_Pert",
            "Hydro_Pert",
            "MAnth",
            "Barr_Cast",
            "pert_maj",
            "pression",
            "press_distance",
            "Comment_DescSite",
            "Eau_SurfLib",
            "Lien_Hydro",
            "Lien_Hydro_Type",
            "Litiere_Noir",
            "Effet_Rhizo",
            "Ecorc_Erod",
            "Inond",
            "Satur_Surf",
            "Lign_Marqu_Eau",
            "Debris_Depot",
            "Odeur_Souf",
            "Racin_Hors",
            "Mousse_Tronc",
            "Souch_Hyper",
            "Lentic_Hyper",
            "Racin_Surf",
            "Racin_Adven",
            "Comment_Hydro",
            "Class_Draing",
            "prof_rac",
            "Prof_Roc",
            "Prof_Nap",
            "Cas_Cpx",
            "Draing_Oblq",
            "type_lit",
            "Epais_Lit",
            "sol_redox",
            "sol_reduct",
            "veget_mh",
            "RecTot_Calc",
            "RecAbsTot_Herb",
            "RecAbsTot_Arbo",
            "RecAbsTot_Arbu",
            "Bilan_Verif",
            "Hyd_Prim",
            "Hyd_Sec",
            "Bil_Hyd",
            "Bil_Drain",
            "Bil_Folisol",
            "Bil_SolHydro",
            "Veg_DomH",
            "Veg_DomNH",
            "Bil_Veg",
            "Bilan_MH",
            "Bilan_Spec",
            "type_mh",
            "tourb_type",
            "Bil_Comment",
        ]

        sections = {
            "Général": [
                "type_mh",
            ],
            "1 - Informations générale": [
                "Nom_Station",
                "Type_Peupl",
                "Typ_Peupl_Det",
                "Date",
                "Heure",
                "Evalu_Princ",
                "num_echant",
            ],
            "2 - Description site": [
                "Contexte",
                "Situat",
                "FormTerr",
                "Depress",
                "Veg_Pert",
                "Sol_Pert",
                "Hydro_Pert",
                "MAnth",
                "Barr_Cast",
                "pert_maj",
                "pression",
                "press_distance",
                "Comment_DescSite",
            ],
            "Micro-dépression": [
                "Depres_Pct",
                "Montic_Pct",
            ],
            "Type de perturbation": [
            ],
            "3 - Hydrologie": [
                "Eau_SurfLib",
                "Lien_Hydro",
                "Lien_Hydro_Type",
                "Comment_Hydro",
            ],
            "Indicateurs primaires": [
                "Litiere_Noir",
                "Effet_Rhizo",
                "Ecorc_Erod",
                "Inond",
                "Satur_Surf",
                "Lign_Marqu_Eau",
                "Debris_Depot",
                "Odeur_Souf",
            ],
            "Indicateurs secondaires": [
                "Racin_Hors",
                "Mousse_Tronc",
                "Souch_Hyper",
                "Lentic_Hyper",
                "Racin_Surf",
                "Racin_Adven",
            ],
            "4 - Sol": [
                "Class_Draing",
                "prof_rac",
                "Prof_Roc",
                "Prof_Nap",
                "Cas_Cpx",
                "Draing_Oblq",
                "sol_redox",
                "sol_reduct",
            ],
            "Litière": [
                "type_lit",
                "Epais_Lit",
            ],
            "5 - Végétation": [
                "veget_mh",
                "RecTot_Calc",
            ],
            "Recouvrement absolu total": [
                "RecAbsTot_Herb",
                "RecAbsTot_Arbo",
                "RecAbsTot_Arbu",
            ],
            "6 - Bilan": [
                "Bilan_Verif",
                "Bil_Comment",
            ],
            "Bilan": [
                "Hyd_Prim",
                "Hyd_Sec",
                "Bil_Hyd",
                "Bil_Drain",
                "Bil_Folisol",
                "Bil_SolHydro",
                "Veg_DomH",
                "Veg_DomNH",
                "Bil_Veg",
                "Bilan_MH",
                "Bilan_Spec",
            ],
            "Sans titre": [
                "tourb_type",
            ],
        }

        super().__init__("Form_MHH", champs, sections)
