# dialogs/rapport_form_eee_dialog.py

from .base_rapport_dialog import BaseRapportDialog

class RapportForm_eeeDialog(BaseRapportDialog):
    def __init__(self):

        champs = [
            "id_act",
            "courriel",
            "precision",
            "regne",
            "ong_site",
            "ong_suivi",
            "ong_intervention",
            "ong_signalement",
            "ong_proprietaire",
            "site",
            "zgie",
            "region",
            "Munic",
            "mrc",
            "Respo",
            "Milieu",
            "Repere",
            "Contrainte",
            "categorie",
            "EEE_Type",
            "lat_flore",
            "autre_sp",
            "autre_nom_latin",
            "SP_autre",
            "NbrVeg",
            "EEE_Densite",
            "Superf_m2",
            "StadeDev",
            "site_autre_stade",
            "site_stade_1",
            "site_stade_2",
            "site_stade_3",
            "site_stade_4",
            "site_stade_5",
            "cause_probag",
            "hote",
            "Trt_av",
            "Trt_avQui",
            "Trt_avType",
            "TraitRecom",
            "EEE_Comment",
            "photo1",
            "suivi_pres",
            "suivi_graines",
            "suivi_superf",
            "Sup_m2_E",
            "suivi_superf_notes",
            "interv_type",
            "interv_type_sec",
            "Reveg",
            "Trait_Supm2",
            "interv_nbr_plants_p",
            "interv_nbr_plants_j",
            "interv_nbr_plants_m",
            "interv_nbr_plants_f",
            "interv_nbr_plants_g",
            "interv_nbr_plants",
            "interv_duree",
            "interv_nbr_pers",
            "interv_effort",
            "Difficulte_lutte",
            "comm2",
            "photo2",
            "Ann_Decouv",
            "cont_notes",
            "valid_ou_nouv",
            "Signaleur",
            "signaleur_contact",
            "comm3",
            "photo3",
            "sp_faune",
            "lat_faune",
            "sp_champi",
            "lat_champi",
            "nb_individus",
        ]

        sections = {
            "Général": [
                "zgie",
                "Respo",
                "Repere",
                "Contrainte",
                "SP_autre",
                "NbrVeg",
                "EEE_Densite",
                "Superf_m2",
                "StadeDev",
                "site_autre_stade",
                "cause_probag",
                "suivi_graines",
                "sp_faune",
                "lat_faune",
            ],
            "Type d'observation": [
                "id_act",
                "courriel",
                "precision",
                "regne",
            ],
            "Il est recommandé de remplir un formulaire Activité de détection avant de réaliser une observation EEE": [
            ],
            "Espèces floristiques": [
                "ong_site",
                "ong_suivi",
                "ong_intervention",
                "ong_signalement",
                "ong_proprietaire",
            ],
            "Site": [
                "EEE_Comment",
                "photo1",
            ],
            "Localisation": [
                "site",
                "region",
                "Munic",
                "mrc",
                "Milieu",
            ],
            "Observations": [
                "categorie",
                "nb_individus",
                "hote",
                "Trt_av",
            ],
            "Préciser l'espèce autre": [
                "autre_sp",
                "autre_nom_latin",
            ],
            "Si autre, préciser dans le champ commentaires": [
            ],
            "Choisir les stades de développement présents, du plus nombreux au moins nombreux": [
                "site_stade_1",
                "site_stade_2",
                "site_stade_3",
                "site_stade_4",
                "site_stade_5",
            ],
            "Traitement": [
                "Trt_av",
                "TraitRecom",
            ],
            "Traitement passé": [
                "Trt_avQui",
                "Trt_avType",
            ],
            "Suivi": [
                "suivi_pres",
                "EEE_Comment",
                "photo1",
            ],
            "Superficie de la colonie": [
                "suivi_superf",
            ],
            "Superficie": [
                "Sup_m2_E",
                "suivi_superf_notes",
            ],
            "Intervention": [
                "comm2",
                "photo2",
            ],
            "Type d'intervention": [
                "interv_type",
                "interv_type_sec",
                "Reveg",
                "Trait_Supm2",
            ],
            "Nombre de plants traités": [
                "interv_nbr_plants_p",
                "interv_nbr_plants_j",
                "interv_nbr_plants_m",
                "interv_nbr_plants_f",
                "interv_nbr_plants_g",
                "interv_nbr_plants",
            ],
            "Effort d'intervention": [
                "interv_duree",
                "interv_nbr_pers",
                "interv_effort",
                "Difficulte_lutte",
            ],
            "Signalement": [
                "Ann_Decouv",
                "cont_notes",
                "valid_ou_nouv",
                "categorie",
                "EEE_Type",
                "lat_flore",
                "comm3",
                "photo3",
            ],
            "Validation": [
                "Signaleur",
                "signaleur_contact",
            ],
            "Propriétaire": [
            ],
            "Faune, champignons ou autre": [
                "EEE_Comment",
                "photo1",
            ],
            "Sans titre": [
                "sp_champi",
                "lat_champi",
            ],
        }

        super().__init__("Form_EEE", champs, sections)
